// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL_e8S3KGBaqqpJybq6t78JJdZOM_hIl0',
    appId: '1:566841533356:web:7c0f81d934f54609f41009',
    messagingSenderId: '566841533356',
    projectId: 'wallet-fpt',
    authDomain: 'wallet-fpt.firebaseapp.com',
    storageBucket: 'wallet-fpt.appspot.com',
    measurementId: 'G-1WP3Y5090W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfDj95PpyYIi287Z5eu5wI3keDFFE13sw',
    appId: '1:566841533356:android:1ca86c4d5082a219f41009',
    messagingSenderId: '566841533356',
    projectId: 'wallet-fpt',
    storageBucket: 'wallet-fpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYCsElJzD1R_Ws8flAX3PUoMGV_p-6ELg',
    appId: '1:566841533356:ios:7e4492f8c870e332f41009',
    messagingSenderId: '566841533356',
    projectId: 'wallet-fpt',
    storageBucket: 'wallet-fpt.appspot.com',
    androidClientId: '566841533356-0q3i7av8jq4mmvkr61tl7hvgn656auoh.apps.googleusercontent.com',
    iosClientId: '566841533356-5ip37cotkue0rs5jnje8c0gn4efsdhvv.apps.googleusercontent.com',
    iosBundleId: 'com.MarketGO.MarketGO',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYCsElJzD1R_Ws8flAX3PUoMGV_p-6ELg',
    appId: '1:566841533356:ios:7e4492f8c870e332f41009',
    messagingSenderId: '566841533356',
    projectId: 'wallet-fpt',
    storageBucket: 'wallet-fpt.appspot.com',
    androidClientId: '566841533356-0q3i7av8jq4mmvkr61tl7hvgn656auoh.apps.googleusercontent.com',
    iosClientId: '566841533356-5ip37cotkue0rs5jnje8c0gn4efsdhvv.apps.googleusercontent.com',
    iosBundleId: 'com.MarketGO.MarketGO',
  );
}
